# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "project"
client_id = "274529d233b60d45ead01e688b942852"
application_url = "https://toner-shaped-bra-linear.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_product_listings,read_publications,read_orders,read_customers,read_payment_terms"

[auth]
redirect_urls = [
  "https://toner-shaped-bra-linear.trycloudflare.com/auth/callback",
  "https://toner-shaped-bra-linear.trycloudflare.com/auth/shopify/callback",
  "https://toner-shaped-bra-linear.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hoang-dinh-hung.myshopify.com"
